apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: observability
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: ingress-nginx-logs
        prospector.scanner.symlinks: true
        parsers:
          - container: ~
        paths:
          - /var/log/containers/*.log

    processors:
      - add_kubernetes_metadata:
          host: ${KUBE_NODE_NAME}
          matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      # فقط لاگ‌های ingress-nginx رو نگه دار، بقیه رو بنداز دور
      - drop_event:
          when:
            not:
              equals:
                kubernetes.namespace: "ingress-nginx"

      # برای ingress چون JSON نیست، decode_json_fields عملاً کاری نمی‌کنه؛
      # می‌تونیم فعلاً حذفش کنیم. اگر بعداً بعضی appها JSON بودن، دوباره اضافه می‌کنیم.

      - drop_fields:
          fields:
            - "agent"
            - "ecs"
            - "host"
            - "input"
            - "log.offset"
            - "log.file.path"
            - "log.flags"
          ignore_missing: true

    output.logstash:
      hosts: ["10.211.55.63:5044"]
      # اگر Logstash بیرون کلاستر یا با IP هست، این آدرس رو با IP/Host خودت عوض کن.

    logging.level: info
    logging.to_files: false
